name: Build and Push Docker Image for PRD
on:
  push:
    branches:
      - main

env:
  HUB_URI: ${{ secrets.HUB_URI }}
  HUB_USERNAME: ${{ secrets.USERNAME }}
  HUB_PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ HUB_USERNAME }}
          password: ${{ HUB_PASSWORD }}

      - name: Build, tag, and push image to Docker Hub
        id: build-image
        run: |
          docker build -t $HUB_URI:$GITHUB_RUN_NUMBER .
          docker push $HUB_URI:$GITHUB_RUN_NUMBER